
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const About = lazy(() => import("./pages/About.tsx"));
const Admin = lazy(() => import("./pages/Admin.tsx"));
const AdminTools = lazy(() => import("./pages/AdminTools.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const DevTools = lazy(() => import("./pages/DevTools.tsx"));
const LuxuryShowcase = lazy(() => import("./pages/LuxuryShowcase.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Properties = lazy(() => import("./pages/Properties.tsx"));
const PropertyDetail = lazy(() => import("./pages/PropertyDetail.tsx"));
const PropertyDetailWrapper = lazy(() => import("./pages/PropertyDetailWrapper.tsx"));
const PropertyEdit = lazy(() => import("./pages/PropertyEdit.tsx"));
const PropertyGenerator = lazy(() => import("./pages/PropertyGenerator.tsx"));
const PropertyListing = lazy(() => import("./pages/PropertyListing.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const ScriptUploader = lazy(() => import("./pages/ScriptUploader.tsx"));
const VerifyEmail = lazy(() => import("./pages/VerifyEmail.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about", element: <About />},
	{ path: "/admin", element: <Admin />},
	{ path: "/admin-tools", element: <AdminTools />},
	{ path: "/admintools", element: <AdminTools />},
	{ path: "/", element: <App />},
	{ path: "/contact", element: <Contact />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/dev-tools", element: <DevTools />},
	{ path: "/devtools", element: <DevTools />},
	{ path: "/luxury-showcase", element: <LuxuryShowcase />},
	{ path: "/luxuryshowcase", element: <LuxuryShowcase />},
	{ path: "/profile", element: <Profile />},
	{ path: "/properties", element: <Properties />},
	{ path: "/property-detail", element: <PropertyDetail />},
	{ path: "/propertydetail", element: <PropertyDetail />},
	{ path: "/property-detail-wrapper", element: <PropertyDetailWrapper />},
	{ path: "/propertydetailwrapper", element: <PropertyDetailWrapper />},
	{ path: "/property-edit", element: <PropertyEdit />},
	{ path: "/propertyedit", element: <PropertyEdit />},
	{ path: "/property-generator", element: <PropertyGenerator />},
	{ path: "/propertygenerator", element: <PropertyGenerator />},
	{ path: "/property-listing", element: <PropertyListing />},
	{ path: "/propertylisting", element: <PropertyListing />},
	{ path: "/register", element: <Register />},
	{ path: "/script-uploader", element: <ScriptUploader />},
	{ path: "/scriptuploader", element: <ScriptUploader />},
	{ path: "/verify-email", element: <VerifyEmail />},
	{ path: "/verifyemail", element: <VerifyEmail />},

];
